replicaCount: 1

image:
  repository: ghcr.io/g-holali-david/backup-operator
  pullPolicy: IfNotPresent
  tag: ""

leaderElect: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: true
  name: backup-operator

rbac:
  create: true
